# Generated by Django 4.2.5 on 2025-04-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='venueavailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='venueavailability',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venueavailability',
            name='repeat_weekly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venueavailability',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AddConstraint(
            model_name='venueavailability',
            constraint=models.UniqueConstraint(fields=('venue', 'date', 'opening_time', 'closing_time'), name='unique_date_availability'),
        ),
        migrations.AddConstraint(
            model_name='venueavailability',
            constraint=models.UniqueConstraint(fields=('venue', 'day_of_week', 'opening_time', 'closing_time'), name='unique_weekly_availability'),
        ),
    ]
